[package]
name = "alacritty_startup"
version = "0.1.0"
edition = "2021"
description = "Sets various settings in my alacritty config based on external conditions."

[dependencies]
dirs = "5"
serde = { version = "1", features = ["derive"] }
toml = "0.8.10"
xrandr = "0.2.0"
